# Generated by Django 6.0.1 on 2026-01-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Equipe Interna'), ('franchisee', 'Franqueados')], default='internal', max_length=20),
        ),
    ]
