# Generated by Django 5.2.10 on 2026-01-30 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_document_visibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='document',
            name='filename',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Interno'), ('franchisee', 'Franqueado'), ('customer', 'Cliente')], default='internal', max_length=20),
        ),
        migrations.CreateModel(
            name='LearnedKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título resumido do conhecimento', max_length=255)),
                ('content', models.TextField(help_text='O que foi aprendido')),
                ('source', models.CharField(default='chat', help_text='Origem: chat, manual, etc', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se False, não será usado nas respostas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conhecimento Aprendido',
                'verbose_name_plural': 'Conhecimentos Aprendidos',
                'ordering': ['-created_at'],
            },
        ),
    ]
